<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Raumverwaltung.aspx.cs" Inherits="Raumverwaltung.View.Raumverwaltung" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            &nbsp;
            <asp:ImageButton
                ID="Home"
                runat="server"
                OnClick="btnHome_Click"
                ImageUrl="E:\Berufsschule\AWE_MEI\003 Gruppenprojekt - Krankenhausverwaltung\Raumverwaltung\Raumverwaltung\Images\home.png"
                Height="25px"
                ToolTip="zurück"
                HorizontalContentAlignment="Left" />
            &nbsp;
            <asp:LoginName ID="LoginName1" runat="server" />
            &nbsp;<asp:LoginStatus ID="LoginStatus1" runat="server" OnLoggingOut="LoginStatus1_LoggingOut" />
        </div>
        <div>
            <asp:Table ID="Table1" runat="server">
                <asp:TableRow runat="server">
                    <asp:TableCell runat="server">
                        <asp:GridView
                            ID="Grid1"
                            runat="server"
                            AutoGenerateDeleteButton="False"
                            AutoGenerateEditButton="False"
                            AutoGenerateSelectButton="True"
                            OnRowCancelingEdit="Grid1_RowCancelingEdit"
                            OnRowDeleting="Grid1_RowDeleting"
                            OnRowEditing="Grid1_RowEditing"
                            OnRowUpdating="Grid1_RowUpdating" 
                            OnRowDataBound="Grid1_RowDataBound"
                            ShowHeaderWhenEmpty="True"
                            AutoGenerateColumns="False"
                            >
                            <Columns>
                                <asp:BoundField DataField="ID" HeaderText="ID" />
                                <asp:TemplateField  HeaderText="Zweck">
                                    <ItemTemplate>
                                         <asp:DropDownList ID="ddlZweck" runat="server" OnDataBound="ddltest_DataBound"/>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:CheckBoxField DataField="außer Betrieb" HeaderText="außer Betrieb" />
                            </Columns>
                        </asp:GridView> 
                    </asp:TableCell>
                    <asp:TableCell runat="server">
                        <asp:Button ID="btnAddRaum" runat="server" Text="Hinzufügen" OnClick="btnAddRaum_Click" />
                    </asp:TableCell>
                </asp:TableRow>
            </asp:Table>
        </div>
        <div>
            <asp:Table ID="Table2" runat="server" Visible="true">
                <asp:TableRow runat="server">
                    <asp:TableCell runat="server">
                        <asp:GridView
                            ID="Grid2"
                            runat="server"
                            AutoGenerateDeleteButton="False"
                            AutoGenerateEditButton="False"
                            AutoGenerateSelectButton="True"
                            OnRowCancelingEdit="Grid2_RowCancelingEdit"
                            OnRowDeleting="Grid2_RowDeleting"
                            OnRowEditing="Grid2_RowEditing"
                            OnRowUpdating="Grid2_RowUpdating" 
                            ShowHeaderWhenEmpty="True"/>
                    </asp:TableCell>
                    <asp:TableCell runat="server">
                        <asp:Button ID="btnAddPersZimmer" runat="server" Text="Hinzufügen" OnClick="btnAddPersZimmer_Click" />
                    </asp:TableCell>
                </asp:TableRow>
            </asp:Table>
            <asp:GridView 
                ID="Grid3"
                runat="server"
                AutoGenerateSelectButton="True"
                OnRowCancelingEdit="Grid2_RowCancelingEdit"
                OnRowDeleting="Grid2_RowDeleting"
                OnRowEditing="Grid2_RowEditing"
                OnRowUpdating="Grid2_RowUpdating" 
                OnRowDataBound="Grid3_RowDataBound" 
                ShowHeaderWhenEmpty="True"
                AutoGenerateColumns="False"
                >
                <Columns>
                    <asp:BoundField HeaderText="ID" />
                    <asp:TemplateField HeaderText="Zweck">
                        <EditItemTemplate>
                             <asp:DropDownList ID="ddlZweck" runat="server"/>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblZweck" runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="außer Betrieb">
                        <EditItemTemplate>
                            <asp:CheckBox ID="cbABetrieb" runat="server" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:CheckBox ID="cbABetrieb" runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:CheckBoxField Text="Test" />
                </Columns>
                </asp:GridView>
                <br />
                <asp:CheckBox ID="CB1" runat="server" />
                <asp:DropDownList ID="ddltest" runat="server" OnDataBound="ddltest_DataBound"/>
                <br />
        </div>
    </form>
</body>
</html>
